### ISSUE TITLE
How do you get an invitation to the Fast Track Slack team?

### ISSUE THREAD

**Issue by tachyonlabs** [gabor-meszaros/aad-certification-faq#1]
Re "Some of the benefits of taking the Associate Android Developer Fast Track is that you get access to a Slack team where you get direct answers for your questions about the exam.":

After seeing androidnanodegree.slack.com mentioned in Udacity forums I was able to get an invitation to join by going to https://androidnanodegree.herokuapp.com/ but there is practically no traffic on it these days, and nothing about the Fast Track program. I looked through my "Welcome to Associate Android Developer Fast Track program!" email, other Udacity emails, the forums, the FAQ, etc. but can't find anything about a Fast Track Slack team. I even had posted a question about it in the forums a while ago but the Forum Mentors didn't know anything about it.

So yeah, how did you find out about it and get an invitation?

**Comment by gabor-meszaros** [comment]
Hm, you are right. It isn't the Associate Android Developer Fast Track Slack Team but the Android Scholarships Slack Team. We have a very active community there (~1000 people, ~250 people on the certification exam channel). I am not sure if you can join unless you are in the EU Android Scholarship students, but I'll ask one of our forum mentors.

**Comment by tachyonlabs** [comment]
Thanks! I'm not in the EU or a scholarship student, but that Slack team sounds great -- it would improve my experience of the Fast Track program a *lot* if it also included the opportunity to be part of an actual community of students.

**Comment by gabor-meszaros** [comment]
I asked one of our forum mentors. Currently, the EU Scholarship Slack Team is only available for the Scholarship members. He does not aware of Fast Track giving you access to a Slack channel. Scholarship students get some extras like the Slack channel, the hackathons, and for selected cities face-to-face connect sessions. Maybe in the future they will provide these things to regular Fast Track students too.

He knows that there is a Android Nanodegree Slack Team that was opened by the students. Maybe that is what you mentioned (androidnanodegree.slack.com). I am not member of that team so I do not know. Of course the coach-supported forum is there for questions, but I agree on that Slack is better for quick questions/answers (although it is not really searchable).

I am sorry. If you think that I can help you, feel free to contact me ([contact info](https://gabor.meszaros.name/#contact)).

**Comment by gabor-meszaros** [comment]
We discussed the possibilities in email, but the scholarship has ended. I close this issue.
